### ISSUE TITLE
Error: '\U' (Problem with path)

### ISSUE THREAD

**Issue by benjaminschlegel** [ccs-amsterdam/ccsAnnotator#1]
The package gives an error message when using start_annotator. I debugged the package and found the problem. In the helper function create_plumber_file() you use writeLines() which replaces \\\\ by \\ as \\ is the escape sign of R. Therefore the path in the new created temp file is c:\\User\\.... instead of c:\\\\User\\\\. This can be fixed with replacing \\\\ by \\\\\\\\ in the start_server_script string with gsub(). Add added you below the fixed function.

```
create_plumber_file = function (server_script) 
{
  start_server_file = tempfile(fileext = ".r")
  start_server_script = sprintf("library(annotinder)\ntryCatch(plumber::pr_run(plumber::pr('%s'), docs=F, port=8000), error=function(e) NULL)", 
                                server_script)
  start_server_script = gsub("\\\\", "\\\\\\\\", start_server_script) # new line
  writeLines(start_server_script, start_server_file)
  start_server_file
}
```

**Comment by kasperwelbers** [comment]
Thanks! At the moment I don't have a windows computer at my disposal, but I'll check it out once I do.

**Comment by kasperwelbers** [comment]
I never really found that windows computer, but your suggestion didn't break anything for linux or mac, so I included it. Thanks again for spotting and fixing the issue!
