### ISSUE TITLE
Return user assigned IDs with in results

### ISSUE THREAD

**Issue by JBGruber** [ccs-amsterdam/ccsAnnotator#2]
I wondered why I couldn't get the IDs I assigned when returning results. I think this line should be changed:

https://github.com/ccs-amsterdam/annotinder-r/blob/3c9f9ce87c68c93bac572d327bb60e48a58191e7/R/gimme_annotations.r#L33

I think it would make more sense to return the **external_id**. I.e.: `dplyr::bind_cols(id = annotations$external_id[i], unit_status=a$status, dplyr::as_tibble(a$annotation))`

**Comment by kasperwelbers** [comment]
Ah thanks! I added the external ids later when working on annotinder-server, and simply forgot to add this to the local R server
